### ISSUE TITLE
Using effective dot with infix causes unnecessary flips

### ISSUE THREAD

**Issue by stuartpb** [bmillwood/pointfree#23]
Using http://pointfree.io/, I passed in this as input:

```haskell
bitMaybe p x = p x `postulate` enumToDigit
```

This was pointfree's suggested formulation:

```haskell
bitMaybe = flip flip enumToDigit . (postulate .)
```

However, after a little legwork, I found that it could be specified more clearly as

```haskell
bitMaybe = ((`postulate` enumToDigit) .)
```

and, indeed, passing this input to pointfree is idempotent.

Is there an improvement that could be made here to get pointfree to suggest the latter over the former?

**Comment by stuartpb** [comment]
Also, is there a cleaner way to express <code>((\`further\` enumToDigit) .)</code> without as many parentheses? <code>(.) (\`further\` enumToDigit)</code> feels closer to the kind of thing I'm thinking, but that's still just as many parens (and it uses dot in an unusual way).

**Comment by stuartpb** [comment]
Another example of an input that feels like it could has a more-smoothly-infixed formulation than pointfree's current output (though I'm not sure what it'd be):

```haskell
latter xs = (>= midpoint xs)
```

Currently, pointfree suggests this:

```haskell
latter = flip (>=) . midpoint
```

**Comment by bmillwood** [comment]
I think as it currently stands this issue is too broad -- I don't think we've nailed down a specific way to improve things or even a specific thing to improve.
