### ISSUE TITLE
bug in alpha-renaming

### ISSUE THREAD

**Issue by int-e** [bmillwood/pointfree#30]
I've just fixed a bug in lambdabot's `@pl` that leads to faulty output. For example, `@pl \x -> \x y -> x` would result in `const (const id)` instead of `const const`.

The same problem is present in `pointfree`, so you may be interested in the fix:

https://github.com/lambdabot/lambdabot/commit/eebe60ac0700dcfbd34ea4870fa3286e7fb4a58b

The root cause is that `\x x y -> x` is alpha-renamed to `\$0 $1 $1 -> $1` instead of `\$0 $1 $2 -> $2`, breaking the internal assumption of the `@pl` code that after alpha-renaming, variable names are *locally unique*.

**Comment by bmillwood** [comment]
Thanks, and in c515b45b995ace8f85ddd72630cc44c38accef55 I added a test.

(How come lambdabot doesn't use this library, btw?)
